name: Deploy Nomad Jobs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nomad CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/nomad/1.6.2/nomad_1.6.2_linux_amd64.zip -o nomad.zip
          unzip nomad.zip
          sudo mv nomad /usr/local/bin/

      - name: Convert backend job to JSON
        run: |
          nomad job run -output infra/nomad/backend.job.hcl > backend.json

      - name: Deploy backend job
        run: |
          curl -X POST https://perle.nomad.100do.se/v1/jobs \
            -H "Content-Type: application/json" \
            --data-binary @backend.json

      - name: Convert worker job to JSON
        run: |
          nomad job run -output infra/nomad/worker.job.hcl > worker.json

      - name: Deploy worker job
        run: |
          curl -X POST https://perle.nomad.100do.se/v1/jobs \
            -H "Content-Type: application/json" \
            --data-binary @worker.json

      - name: Convert frontend job to JSON
        run: |
          nomad job run -output infra/nomad/frontend.job.hcl > frontend.json

      - name: Deploy frontend job
        run: |
          curl -X POST https://perle.nomad.100do.se/v1/jobs \
            -H "Content-Type: application/json" \
            --data-binary @frontend.json