# Stage 1: Build the frontend app with Node.js
FROM node:20 AS builder

WORKDIR /app

COPY . .
RUN npm ci && npm run build

# Stage 2: Serve the built files
FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist /app/dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]

