name: Deploy Nomad Jobs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NOMAD_ADDR: "https://perle.nomad.100do.se"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nomad CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/nomad/1.6.2/nomad_1.6.2_linux_amd64.zip -o nomad.zip
          unzip nomad.zip
          sudo mv nomad /usr/local/bin/

      - name: Deploy backend job
        run: |
          nomad job run infra/nomad/backend.job.hcl

      - name: Deploy worker job
        run: |
          nomad job run infra/nomad/worker.job.hcl

      - name: Deploy frontend job
        run: |
          nomad job run infra/nomad/frontend.job.hcl

      - name: Deploy loadbalancer job
        run: |
          nomad job run infra/nomad/loadbalancer.job.hcl