name: Deploy to Nomad via API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nomad (CLI needed for HCL → JSON)
        run: |
          curl -fsSL https://releases.hashicorp.com/nomad/1.6.2/nomad_1.6.2_linux_amd64.zip -o nomad.zip
          unzip nomad.zip
          sudo mv nomad /usr/local/bin/

      - name: Convert job to JSON
        run: |
          nomad job run -output jobs/backend.nomad.hcl > job.json

      - name: Deploy Nomad job via API
        run: |
          curl -X POST https://perle.nomad.100do.se/v1/jobs \
            -H "Content-Type: application/json" \
            --data-binary @job.json